

spring:
  datasource:                                           # \u6570\u636E\u6E90\u7684\u76F8\u5173\u914D\u7F6E
    type: com.zaxxer.hikari.HikariDataSource          # \u6570\u636E\u6E90\u7C7B\u578B\uFF1AHikariCP
    driver-class-name: com.mysql.jdbc.Driver          # mysql\u9A71\u52A8
    url: jdbc:mysql://39.106.121.113:3306/app?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=UTC&useSSL=false
    username: root
    password: 123456
    hikari:
      connection-timeout: 30000       # \u7B49\u5F85\u8FDE\u63A5\u6C60\u5206\u914D\u8FDE\u63A5\u7684\u6700\u5927\u65F6\u957F\uFF08\u6BEB\u79D2\uFF09\uFF0C\u8D85\u8FC7\u8FD9\u4E2A\u65F6\u957F\u8FD8\u6CA1\u53EF\u7528\u7684\u8FDE\u63A5\u5219\u53D1\u751FSQLException\uFF0C \u9ED8\u8BA4:30\u79D2
      minimum-idle: 5                 # \u6700\u5C0F\u8FDE\u63A5\u6570
      maximum-pool-size: 20           # \u6700\u5927\u8FDE\u63A5\u6570
      auto-commit: true               # \u81EA\u52A8\u63D0\u4EA4
      idle-timeout: 600000            # \u8FDE\u63A5\u8D85\u65F6\u7684\u6700\u5927\u65F6\u957F\uFF08\u6BEB\u79D2\uFF09\uFF0C\u8D85\u65F6\u5219\u88AB\u91CA\u653E\uFF08retired\uFF09\uFF0C\u9ED8\u8BA4:10\u5206\u949F
      pool-name: DateSourceHikariCP     # \u8FDE\u63A5\u6C60\u540D\u5B57
      max-lifetime: 1800000           # \u8FDE\u63A5\u7684\u751F\u547D\u65F6\u957F\uFF08\u6BEB\u79D2\uFF09\uFF0C\u8D85\u65F6\u800C\u4E14\u6CA1\u88AB\u4F7F\u7528\u5219\u88AB\u91CA\u653E\uFF08retired\uFF09\uFF0C\u9ED8\u8BA4:30\u5206\u949F 1800000ms
      connection-test-query: SELECT 1
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
server:
  port: 8082